from app.database.database import SessionLocal
from app.models.infrastructure import InfrastructureAsset

assets = [
    {
        "id": "BR-001",
        "name": "Prakasam Barrage",
        "asset_type": "Barrage",
        "location": "Vijayawada",
        "district": "NTR",
        "latitude": 16.5165,
        "longitude": 80.6150,
        "built_year": 1957,
        "design_life": 100,
        "condition": "Good",
        "health_score": 89,
        "risk_level": "Low",
        "risk_score": 18,
        "remaining_useful_life": 18,
        "owner": "Government",
        "material": "Concrete",
        "status": "Operational",
        "source": "Initial AP Infrastructure Dataset",
        "source_id": "AP-001"
    },
    {
        "id": "BR-002",
        "name": "Godavari Bridge",
        "asset_type": "Bridge",
        "location": "Rajahmundry",
        "district": "East Godavari",
        "latitude": 17.0005,
        "longitude": 81.7768,
        "built_year": 1974,
        "design_life": 75,
        "condition": "Warning",
        "health_score": 71,
        "risk_level": "High",
        "risk_score": 78,
        "remaining_useful_life": 7,
        "owner": "Government",
        "material": "Steel and Concrete",
        "status": "Under Inspection",
        "source": "Initial AP Infrastructure Dataset",
        "source_id": "AP-002"
    },
    {
        "id": "DM-001",
        "name": "Polavaram Project",
        "asset_type": "Dam",
        "location": "Polavaram",
        "district": "Eluru",
        "latitude": 17.2646,
        "longitude": 81.6435,
        "built_year": 2025,
        "design_life": 100,
        "condition": "Good",
        "health_score": 90,
        "risk_level": "Medium",
        "risk_score": 35,
        "remaining_useful_life": 80,
        "owner": "Government",
        "material": "Concrete",
        "status": "Operational",
        "source": "Initial AP Infrastructure Dataset",
        "source_id": "AP-003"
    },
    {
        "id": "AP-001",
        "name": "Vijayawada Airport",
        "asset_type": "Airport",
        "location": "Gannavaram",
        "district": "Krishna",
        "latitude": 16.5304,
        "longitude": 80.7968,
        "built_year": 1981,
        "design_life": 50,
        "condition": "Good",
        "health_score": 86,
        "risk_level": "Low",
        "risk_score": 22,
        "remaining_useful_life": 15,
        "owner": "AAI",
        "material": "Concrete",
        "status": "Operational",
        "source": "Initial AP Infrastructure Dataset",
        "source_id": "AP-004"
    },
    {
        "id": "PT-001",
        "name": "Visakhapatnam Port",
        "asset_type": "Port",
        "location": "Visakhapatnam",
        "district": "Visakhapatnam",
        "latitude": 17.6868,
        "longitude": 83.2185,
        "built_year": 1933,
        "design_life": 100,
        "condition": "Good",
        "health_score": 84,
        "risk_level": "Medium",
        "risk_score": 38,
        "remaining_useful_life": 20,
        "owner": "Visakhapatnam Port Authority",
        "material": "Mixed",
        "status": "Operational",
        "source": "Initial AP Infrastructure Dataset",
        "source_id": "AP-005"
    },
    {
        "id": "BR-003",
        "name": "NTR Bridge",
        "asset_type": "Bridge",
        "location": "Vijayawada",
        "district": "NTR",
        "latitude": 16.5165,
        "longitude": 80.6350,
        "built_year": 1995,
        "design_life": 80,
        "condition": "Good",
        "health_score": 85,
        "risk_level": "Low",
        "risk_score": 25,
        "remaining_useful_life": 45,
        "owner": "Government",
        "material": "Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-006"
    },
    {
        "id": "RD-001",
        "name": "NH16 - Vijayawada Section",
        "asset_type": "Road",
        "location": "NH16 Highway",
        "district": "Krishna",
        "latitude": 16.5200,
        "longitude": 80.6500,
        "built_year": 2005,
        "design_life": 30,
        "condition": "Fair",
        "health_score": 62,
        "risk_level": "Medium",
        "risk_score": 55,
        "remaining_useful_life": 8,
        "owner": "NHAI",
        "material": "Bituminous",
        "status": "Maintenance Required",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-007"
    },
    {
        "id": "PP-001",
        "name": "Thermal Power Station - Vijayawada",
        "asset_type": "Power Plant",
        "location": "Vijayawada",
        "district": "Krishna",
        "latitude": 16.4800,
        "longitude": 80.6800,
        "built_year": 2000,
        "design_life": 50,
        "condition": "Good",
        "health_score": 82,
        "risk_level": "Medium",
        "risk_score": 42,
        "remaining_useful_life": 22,
        "owner": "NTPC",
        "material": "Steel and Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-008"
    },
    {
        "id": "BR-004",
        "name": "Krishna River Crossing",
        "asset_type": "Bridge",
        "location": "Macherla",
        "district": "Guntur",
        "latitude": 15.8500,
        "longitude": 79.5500,
        "built_year": 1988,
        "design_life": 75,
        "condition": "Critical",
        "health_score": 45,
        "risk_level": "High",
        "risk_score": 89,
        "remaining_useful_life": 2,
        "owner": "Government",
        "material": "Steel",
        "status": "Closed for Repairs",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-009"
    },
    {
        "id": "DM-002",
        "name": "Nagarjunasagar Dam",
        "asset_type": "Dam",
        "location": "Nagarjunakonda",
        "district": "Guntur",
        "latitude": 16.6500,
        "longitude": 78.9800,
        "built_year": 1967,
        "design_life": 100,
        "condition": "Good",
        "health_score": 87,
        "risk_level": "Low",
        "risk_score": 20,
        "remaining_useful_life": 35,
        "owner": "Government",
        "material": "Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-010"
    },
    {
        "id": "RD-002",
        "name": "State Highway 5 - Tirupati Bypass",
        "asset_type": "Road",
        "location": "Tirupati",
        "district": "Chittoor",
        "latitude": 13.2150,
        "longitude": 79.8960,
        "built_year": 2008,
        "design_life": 25,
        "condition": "Fair",
        "health_score": 68,
        "risk_level": "Medium",
        "risk_score": 48,
        "remaining_useful_life": 6,
        "owner": "Government",
        "material": "Bituminous",
        "status": "Maintenance Required",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-011"
    },
    {
        "id": "BR-005",
        "name": "Indus Sagar Bridge",
        "asset_type": "Bridge",
        "location": "Ponnaluru",
        "district": "Prakasam",
        "latitude": 14.3500,
        "longitude": 79.8200,
        "built_year": 2002,
        "design_life": 60,
        "condition": "Good",
        "health_score": 83,
        "risk_level": "Low",
        "risk_score": 28,
        "remaining_useful_life": 32,
        "owner": "Government",
        "material": "Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-012"
    },
    {
        "id": "BLD-001",
        "name": "Secretariat Complex - Hyderabad",
        "asset_type": "Building",
        "location": "Hyderabad",
        "district": "Hyderabad",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "built_year": 1950,
        "design_life": 75,
        "condition": "Fair",
        "health_score": 71,
        "risk_level": "Medium",
        "risk_score": 52,
        "remaining_useful_life": 10,
        "owner": "Government",
        "material": "Concrete and Steel",
        "status": "Under Renovation",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-013"
    },
    {
        "id": "PT-002",
        "name": "Krishnapatnam Port",
        "asset_type": "Port",
        "location": "Krishnapatnam",
        "district": "Nellore",
        "latitude": 14.4500,
        "longitude": 79.9833,
        "built_year": 2008,
        "design_life": 50,
        "condition": "Good",
        "health_score": 88,
        "risk_level": "Low",
        "risk_score": 19,
        "remaining_useful_life": 32,
        "owner": "Private",
        "material": "Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-014"
    },
    {
        "id": "RD-003",
        "name": "Outer Ring Road - Hyderabad",
        "asset_type": "Road",
        "location": "Hyderabad",
        "district": "Hyderabad",
        "latitude": 17.4000,
        "longitude": 78.5500,
        "built_year": 2010,
        "design_life": 30,
        "condition": "Excellent",
        "health_score": 92,
        "risk_level": "Low",
        "risk_score": 12,
        "remaining_useful_life": 20,
        "owner": "HMRL",
        "material": "Bituminous",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-015"
    },
    {
        "id": "BR-006",
        "name": "Bowenpally Bridge",
        "asset_type": "Bridge",
        "location": "Hyderabad",
        "district": "Hyderabad",
        "latitude": 17.3650,
        "longitude": 78.4550,
        "built_year": 1975,
        "design_life": 65,
        "condition": "Warning",
        "health_score": 64,
        "risk_level": "High",
        "risk_score": 76,
        "remaining_useful_life": 5,
        "owner": "HMRL",
        "material": "Steel",
        "status": "Urgent Repair",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-016"
    },
    {
        "id": "AP-002",
        "name": "Hyderabad International Airport",
        "asset_type": "Airport",
        "location": "Shamshabad",
        "district": "Hyderabad",
        "latitude": 17.2433,
        "longitude": 78.7697,
        "built_year": 2008,
        "design_life": 60,
        "condition": "Excellent",
        "health_score": 93,
        "risk_level": "Low",
        "risk_score": 8,
        "remaining_useful_life": 38,
        "owner": "GHIAL",
        "material": "Concrete and Steel",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-017"
    },
    {
        "id": "BR-007",
        "name": "Hussain Sagar Bridge",
        "asset_type": "Bridge",
        "location": "Hyderabad",
        "district": "Hyderabad",
        "latitude": 17.3833,
        "longitude": 78.4833,
        "built_year": 1990,
        "design_life": 70,
        "condition": "Good",
        "health_score": 81,
        "risk_level": "Low",
        "risk_score": 26,
        "remaining_useful_life": 37,
        "owner": "HMWSSB",
        "material": "Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-018"
    },
    {
        "id": "DM-003",
        "name": "Osman Sagar Dam",
        "asset_type": "Dam",
        "location": "Hyderabad",
        "district": "Hyderabad",
        "latitude": 17.2667,
        "longitude": 78.5000,
        "built_year": 1908,
        "design_life": 100,
        "condition": "Fair",
        "health_score": 58,
        "risk_level": "High",
        "risk_score": 84,
        "remaining_useful_life": 5,
        "owner": "HMWSSB",
        "material": "Masonry",
        "status": "Heritage - Monitoring Required",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-019"
    },
    {
        "id": "SCH-001",
        "name": "Central University - Hyderabad",
        "asset_type": "School",
        "location": "Hyderabad",
        "district": "Hyderabad",
        "latitude": 17.4500,
        "longitude": 78.4700,
        "built_year": 2004,
        "design_life": 50,
        "condition": "Good",
        "health_score": 86,
        "risk_level": "Low",
        "risk_score": 21,
        "remaining_useful_life": 27,
        "owner": "Government",
        "material": "Concrete",
        "status": "Operational",
        "source": "Enhanced AP Dataset",
        "source_id": "AP-020"
    },
]

db = SessionLocal()

try:
    for item in assets:
        existing = db.query(InfrastructureAsset).filter(
            InfrastructureAsset.id == item["id"]
        ).first()

        if not existing:
            db.add(InfrastructureAsset(**item))

    db.commit()
    print(f"Successfully seeded {len(assets)} infrastructure assets.")

except Exception as e:
    db.rollback()
    print("ERROR:", e)

finally:
    db.close()